### ISSUE TITLE
Can't find Database

### ISSUE THREAD

**Issue by snoydoc** [diksito/url-shortner#1]
Hello,

I've tried to install your project. but i can't. Database missing i think. I've looked in app_data for .mdf file but it dosen't exist.

Any help please?

Regards,
H.Y.

**Comment by diksito** [comment]
Hi,

You need to execute "Updata-Database" in order to apply all migrations in
package manager. The project is model first based.

Best Regards,
Nikolay Angelov

@NikolayAngelov

**Comment by snoydoc** [comment]
Thank you at advance. I needed to update all package component before
itworks. It was a VS issue.

Regards,
H.Y.
