### ISSUE TITLE
Error when shorting url

### ISSUE THREAD

**Issue by tagplus5** [diksito/url-shortner#2]
I past url 
![image](https://cloud.githubusercontent.com/assets/2699260/7903083/e0dbc6a0-07d9-11e5-8b28-957928c58a23.png)
get link, click on it, past same url again and get error
![image](https://cloud.githubusercontent.com/assets/2699260/7903087/f71dbc8e-07d9-11e5-8a2b-210454d85007.png)
![image](https://cloud.githubusercontent.com/assets/2699260/7903089/fca2fa98-07d9-11e5-99cb-ccb8c9823c8f.png)

**Comment by tagplus5** [comment]
![image](https://cloud.githubusercontent.com/assets/2699260/7903108/9d51c76c-07da-11e5-90c6-38daa928dc08.png)
add to home controller for fix this error

**Comment by diksito** [comment]
Thanks for reporting this issue. I will test and commit the fix.
